export const company = [
  {
    key1: "CIN/LLPIN/FCRN",
    prop1: "U20129PN2023PTC224436",
    key2: "Date of Inc.",
    prop2: "10/03/2023",
    key3: "Authorised Capital",
    prop3: "₹30,000.00",
  },
  {
    key1: "ROC Code",
    prop1: "ROC Pune",
    key2: "Date of AGM",
    prop2: "-",
    key3: "Paid up Capital",
    prop3: "₹30,000.00",
  },
  {
    key1: "Company Class",
    prop1: "Private",
    key2: "Date of B/S",
    prop2: "-",
    key3: "Email",
    prop3: "rvmaher1999@gmail.com",
  },
  {
    key1: "Company Category",
    prop1: "Company limited by shares",
    key2: "Company Status",
    prop2: "Active",
    key3: "Listing Status",
    prop3: "Unlisted",
  },
  {
    key1: "Activity Description",
    prop1: "-",
    key2: "CIRP",
    prop2: "-",
    key3: "Filing Status",
    prop3: "-",
  },
  {
    key1: "Active Compliance",
    prop1: "-",
    key2: "Adress other than R/o",
    prop2: "-",
    key3: "Registered Address",
    prop3:
      "DYPATIL INST. OF HO. MNGT,87/88 BY PASS HIGHWAY,Thathawade,Pune,Pune City,Maharashtra,India,411033",
  },
  {
    key1: "Pan",
    prop1: "Locked",
  },
];
